branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: Shareschoolbooks-env
global:
  application_name: share-school-books
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
