# Generated by Django 3.2.7 on 2021-09-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0005_auto_20200611_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(db_index=True, default='01234567891234', max_length=13),
            preserve_default=False,
        ),
    ]
